version: "3.7"
services:
  bot:
    build:
      context: .
      target: test
    command: sh -c "yarn install --frozen-lockfile --non-interactive --production=false && yarn start"
    stdin_open: true
    ports:
      - 80:3000
    environment:
      DISCORD_CLIENT_AUTH_TOKEN: $DISCORD_CLIENT_AUTH_TOKEN
      NODE_ENV: test
      TEST_CHANNEL_ID: 787788250697170955
    volumes:
      - $PWD/:/src
    tmpfs:
      - /cache/yarn
