version: "3.7"
services:
  bot:
    build:
      context: .
      target: test
    command: sh -c "pnpm i && pnpm start"
    stdin_open: true
    ports:
      - 80:3000
    environment:
      DISCORD_CLIENT_AUTH_TOKEN: $DISCORD_CLIENT_AUTH_TOKEN
      NODE_ENV: development
      TEST_CHANNEL_ID: 787788250697170955
      GUILD_ID: 783594092268617766
      BOT_CLIENT_ID: 787162425304154142
    volumes:
      - $PWD/:/src
