# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: "Use Node.Js"
        uses: actions/setup-node@v1
        with:
          node-version: "15.x"
      - name: "Install Dependencies"
        run: yarn install --frozen-lockfile
      - name: "Run Tests"
        env:
          NODE_ENV: test
        run: yarn test
